export const MAIN_COLOR = "var(--surface-strong)"
export const BAGROUND_COLOR = "var(--background)"
export const CONTRAST_COLOR = "var(--text-inverse)"
export const TEXT_STRONG_COLOR = "var(--text-strong)"
export const TEXT_SOFT_COLOR = "var(--text-soft)"
export const BRAND_COLOR = "var(--text-brand)"
